spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  raw-storage:
    s3:
      bucket: ${RAW_STORAGE_S3_BUCKET:itda-raw-records-dev}
      region: ${AWS_REGION:ap-northeast-2}
